### ISSUE TITLE
enum LogLevel name conflict

### ISSUE THREAD

**Issue by Quaker762** [Palm-Studios/sh3redux#35]
On g++6.2.0 I can't build due to [this](https://github.com/Palm-Studios/sh3redux/blob/master/include/SH3/system/log.hpp#L28) line. 

It would seem somewhere, ERROR is already defined (I assume by the compiler?). Changing this to ERR fixes it.

**Comment by z33ky** [comment]
Works on my g++ 6.2.1. What's the exact error-message you get?

**Comment by Quaker762** [comment]
I'm getting an `expected identifier before numeric constant error`

`In file included from E:/MinGW/x86_64-w64-mingw32/include/windows.h:71:0,
                 from E:/MinGW/x86_64-w64-mingw32/include/GL/gl.h:13,
                 from include/SH3/graphics/texture.hpp:23,
                 from E:\Users\Jesse\Documents\Palm Studios\sh3redux-fork\sh3redux\source\SH3\graphics\texture.cpp:12:
include/SH3/system/log.hpp:28:5: error: expected identifier before numeric constant
     ERROR,
     ^
include/SH3/system/log.hpp:28:5: error: expected '}' before numeric constant
include/SH3/system/log.hpp:28:5: error: expected unqualified-id before numeric constant
In file included from E:\Users\Jesse\Documents\Palm Studios\sh3redux-fork\sh3redux\source\SH3\graphics\texture.cpp:13:0:
include/SH3/system/log.hpp:31:1: error: expected declaration before '}' token
 };`

**Comment by z33ky** [comment]
I see. Should get fixed by #38.

**Comment by Quaker762** [comment]
Bizarre, must be some weird Microsoft voodoo
